GET http://localhost:8080/locations/rank
Accept: application/json

###

GET http://localhost:8080/locations/search?keyword=고래의바다
Accept: application/json

###

GET http://localhost:8080/locations/search?keyword=스타벅스 제주 애월
Accept: application/json

###

GET http://localhost:8080/locations/search?keyword=안나올만한키워드
Accept: application/json

###


GET http://localhost:8080/locations/search?keyword=a

###
GET http://localhost:8080/locations/search?keyword=b

###
GET http://localhost:8080/locations/search?keyword=c

###
GET http://localhost:8080/locations/search?keyword=d

###
GET http://localhost:8080/locations/search?keyword=e

###
GET http://localhost:8080/locations/search?keyword=f

###
GET http://localhost:8080/locations/search?keyword=g

###
GET http://localhost:8080/locations/search?keyword=h

###
GET http://localhost:8080/locations/search?keyword=i

###
