GET http://localhost:8080/locations/search?keyword=고래의바다
Accept: application/json

###

GET http://localhost:8080/locations/search?keyword=스타벅스 제주 애월
Accept: application/json

###

GET http://localhost:8080/locations/search?keyword=안나올만한키워드
Accept: application/json

###