# Application 설정
imin:
  jeju:
    search:
      max-result-size: 10
      provider:
        kakao:
          request-size: 5
          api-key: KakaoAK e140ea5e34746b9778dccd2631b382d3
        naver:
          request-size: 5
          api-key: kvN88UoRxdxW6rpFYivh
          secret: 8PpQMn8C0W

    rank:
      # 오차율 0.001
      depth: 5 # hash function 개수
      width: 2000
      minute-threshold: 1 # 수집 단위 (5, 30, 60) 등 60으로 나눌때 나머지가 없는 수
      ranking-size: 10 # 응답할 rank의 수
      cache-times: 2 # minute-threshold * cache-times(분) 동안의 요청만 검색 키워드 목록에 응답한다.

# spring 설정
spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=60s